# Generated by Django 5.0.6 on 2024-06-28 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('U_Auth', '0004_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='drinking',
            field=models.BooleanField(default=False),
        ),
    ]
