# Generated by Django 5.0.6 on 2024-06-28 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('U_Auth', '0005_user_drinking'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rel_status',
            field=models.CharField(choices=[('S', 'Single'), ('M', 'Married'), ('W', 'Widow'), ('D', 'Divorced')], default='S', max_length=1),
        ),
        migrations.AddField(
            model_name='user',
            name='smoke',
            field=models.CharField(choices=[('N', 'No'), ('Y', 'Yes'), ('P', 'Plan to Quit')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='drinking',
            field=models.CharField(choices=[('T', 'Yes'), ('F', 'No'), ('P', 'Plan to Quit')], default='T', max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1),
        ),
    ]
