# Generated by Django 5.0.6 on 2024-06-29 03:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('U_Auth', '0006_user_rel_status_user_smoke_alter_user_drinking_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeEmployer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('designation', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobSeeker',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('job_field', models.CharField(max_length=100)),
                ('experience', models.PositiveIntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
